// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbwmcjxtpuwscxdzijsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1id21janh0cHV3c2N4ZHppanN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzU0MTgsImV4cCI6MjA3MTU1MTQxOH0.45Zi-bCZzYJaqnrgiJkAr4vQt_5EX_8YDyHv58G-bME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});